---
name: My-Warns
version: 2.0.0
main: WolfDen133\My_Warns\Main
api: 4.0.0
author: WolfDen133

permissions:
  warn.command:
    default: op
  removewarn.command:
    default: op
  seewarns.command:
    default: op
  mywarns.command:
    default: true
...
